/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        customPrimary: "rgb(99, 102, 241)",
        customSecondary: "rgb(161, 163, 247)",
        customDarkBg1: "rgb(31, 32, 35)",
        customDarkBg2: "rgb(38, 39, 43)",
        customDarkBg3: "rgb(48, 49, 54)",
        customDarkBg3Hover: "rgb(55, 56, 62)",
        customContentSubtitle: "rgb(178, 184, 205)",
        customGrayBorder: "rgb(255,255,255,0.1)",
        customGrayText: "rgb(174, 178, 183)",
        customDarkBgTransparent: "rgb(31, 32, 35, 0.7)",
        customDarkBgTransparentDarker: "rgb(0,0,0,0.8)",
        customDarkBgTransparentLighter: "rgb(48, 49, 54, 0.7)",
        dark1: "#010102",
        dark1Transparent: "#B3010409",
        dark2: "#0D1117",
        dark3: "#161B22",
        dark4: "#0D0E13",
        dark5: "#101117",
        faqDark: "#111218",
        white1: "#FFFFFF",
        white2: "#F4F2F0",
        white3: "#E8EFF6",
        white4: "#A6B0BB",
        blue1: "#4A86FF",
        blue2: "#111926",
        faqAnswer: "#BFC0CC",
        faqBorder: "#2F303E",
        trialText: "#A3A4B5",
        trialBorder: "#2F303E",
        trialField: "#191D22",
        trialFieldText: "#85889C",
        labelBackground: "#20212B",
        calBorder: "#16171F",
        labelSperator: "#4D4F60",
        tabBg: "#292A36",
        livnoteBg: "#000",
        livnotePrimary: "#8A86E5",
        customGray: "#B4B9BE",
      },
      fontFamily: {
        Inter: ["Inter", "Helvetica", "Arial", "sans-serif"],
        Jakartha: ["Plus Jakarta Sans", "Arial", "sans-serif"],
        JetBrainsMono: ["JetBrains Mono", "monospace"],
        HostGrotesk: ["Host Grotesk", "sans-serif","Helvetica", "Arial", ],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
        // Responsive font sizes
        'hero-mobile': ['2.5rem', { lineHeight: '1.1' }],
        'hero-tablet': ['3.5rem', { lineHeight: '1.1' }],
        'hero-desktop': ['4.5rem', { lineHeight: '1.1' }],
        'hero-xl': ['5.5rem', { lineHeight: '1.1' }],
        'hero-2xl': ['6.5rem', { lineHeight: '1.1' }],
        'heading-mobile': ['1.5rem', { lineHeight: '1.3' }],
        'heading-tablet': ['2rem', { lineHeight: '1.3' }],
        'heading-desktop': ['2.5rem', { lineHeight: '1.3' }],
        'heading-xl': ['3rem', { lineHeight: '1.3' }],
        'subheading-mobile': ['1rem', { lineHeight: '1.4' }],
        'subheading-tablet': ['1.25rem', { lineHeight: '1.4' }],
        'subheading-desktop': ['1.5rem', { lineHeight: '1.4' }],
        'body-mobile': ['0.875rem', { lineHeight: '1.5' }],
        'body-tablet': ['1.125rem', { lineHeight: '1.5' }],
        'body-desktop': ['1.25rem', { lineHeight: '1.5' }],
      },
      screens: {
        xs: "530px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        xll: "1400px",
        "2xl": "1536px",
        "3xl": "1600px",
      },
      boxShadow: {
        glass:
          "0 0 12px rgba(255, 255, 255, 0.1), inset 0 0 12px rgba(255, 255, 255, 0.1), 0 4px 30px rgba(0, 0, 0, 0.2)",
      },
      animation: {
        scroll:
          "scroll var(--animation-duration, 40s) var(--animation-direction, forwards) linear infinite",
        blink: "blink 2s ease-in infinite",
      },

      keyframes: {
        scroll: {
          to: {
            transform: "translate(calc(-50% - 0.5rem))",
          },
        },
        blink: {
          "0% ": { backgroundColor: "transparent" },
          "20%": { background: "#20212B" },
          "80%": { background: "#20212B" },
          "100%": { backgroundColor: "transparent" },
        },
      },
    },
  },
};
