# build and deploy astro landing page

name: build-and-deploy

on:
  push:
    branches: [ "major" ]

jobs:

  build-and-deploy:
    name: bulid 
    runs-on: ubuntu-latest
    environment: prod


    steps:
    - uses: actions/checkout@v3

    - name: Set up npm
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: build astro js
      run: npm run build

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy to AWS
      run: |
        aws s3 cp ./dist/index.html s3://${{ vars.AWS_S3_BUCKET }}
        aws s3 cp ./dist/favicon.svg s3://${{ vars.AWS_S3_BUCKET }}

